title: J. Patino-Echeverria
logo: https://github.com/jpatinoe.png
description: PhD Student in Mathematics
theme: jekyll-theme-minimal

github_username: jpatinoe

header_pages:
  - a-index.md
  - b-about.md
  - c-projects.md
  - d-contact.md
