title: J. Patino-Echeverria
logo: https://github.com/jpatinoe.png
description: PhD Student in Mathematics
theme: jekyll-theme-minimal

github_username: jpatinoe

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md
